[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"

# Netlify subdomain redirect
[[redirects]]
  from = "https://mikeschenkel.netlify.com/*"
  to = "https://mikeschenkel.nl/:splat"
  status = 301
  force = true

# Dotfiles
[[redirects]]
  from = "/dotfiles"
  to = "https://github.com/mikeschenkel/dotfiles"

# 404s
[[redirects]]
  from = "*"
  to = "/404"
  status = 404
